### ISSUE TITLE
Decentralized app store

### ISSUE THREAD

**Issue by luandro** [dweb-camp-2019/projects#9]
Last year I worked on [app hub](https://github.com/open-app/app-hub-mobile/releases), but have stopped working on it for almost an year now. The initial tests seemed to work fine, so it might be worth trying out.

It uses a bunch of interesting technologies like SSB and Dat, both served over GraphQL and made to run on Android.

In case it doesn't work [dat-installer](https://github.com/staltz/dat-installer/releases) works quite well.

**Comment by benhylau** [comment]
Hey @luandro is this still happening? I feel there are a whole bunch of other threads you're in already!

**Comment by luandro** [comment]
Better not :)
